django/models.py
from django.db import models
from users.models import User

class Item(models.Model):
    """
    データ定義クラス
      各フィールドを定義する
    参考：
    ・公式 モデルフィールドリファレンス
    https://docs.djangoproject.com/ja/2.1/ref/models/fields/
    """

    # サンプル項目1 文字列
    sample_1 = models.CharField(
        verbose_name='志望企業',
        max_length=20,
        blank=True,
        null=True,
    )

    # サンプル項目2 メモ
    sample_2 = models.TextField(
        verbose_name='志望理由',
        blank=True,
        null=True,
    )

    # サンプル項目3 整数
    sample_3 = models.IntegerField(
        verbose_name='志望度',
        blank=True,
        null=True,
    )

    # サンプル項目7 日付
    sample_7 = models.DateField(
        verbose_name='提出締切日',
        blank=True,
        null=True,
    )

    # サンプル項目8 日時
    sample_8 = models.DateTimeField(
        verbose_name='提出締め切り時間',
        blank=True,
        null=True,
    )

    # サンプル項目9 選択肢（固定）
    sample_9_choice = (
        (1, '人事'),
        (2, 'SE'),
        (3, '会計事務職'),
    )

    sample_9 = models.IntegerField(
        verbose_name='業界',
        choices=sample_9_choice,
        blank=True,
        null=True,
    )

    # サンプル項目9 選択肢（マスタ連動）
    sample_10 = models.ForeignKey(
        User,
        verbose_name='作成者',
        blank=True,
        null=True,
        related_name='sample_10',
        on_delete=models.SET_NULL,
    )
    
    sample_11 = models.TextField(
        verbose_name='おすすめ',
        blank=True,
        null=True,
    )

    # 以下、管理項目

    # 作成者(ユーザー)
    created_by = models.ForeignKey(
        User,
        verbose_name='作成者',
        blank=True,
        null=True,
        related_name='CreatedBy',
        on_delete=models.SET_NULL,
        editable=False,
    )

    # 作成時間
    created_at = models.DateTimeField(
        verbose_name='作成時間',
        blank=True,
        null=True,
        editable=False,
    )

    # 更新者(ユーザー)
    updated_by = models.ForeignKey(
        User,
        verbose_name='更新者',
        blank=True,
        null=True,
        related_name='UpdatedBy',
        on_delete=models.SET_NULL,
        editable=False,
    )

    # 更新時間
    updated_at = models.DateTimeField(
        verbose_name='更新時間',
        blank=True,
        null=True,
        editable=False,
    )

    def __str__(self):
        """
        リストボックスや管理画面での表示
        """
        return self.sample_1

    class Meta:
        """
        管理画面でのタイトル表示
        """
        verbose_name = 'サンプル'
        verbose_name_plural = 'サンプル'

django/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django_filters.views import FilterView

from .filters import ItemFilterSet
from .forms import ItemForm
from .models import Item
from .inference import AI


# 未ログインのユーザーにアクセスを許可する場合は、LoginRequiredMixinを継承から外してください。
#
# LoginRequiredMixin：未ログインのユーザーをログイン画面に誘導するMixin
# 参考：https://docs.djangoproject.com/ja/2.1/topics/auth/default/#the-loginrequired-mixin

class ItemFilterView(LoginRequiredMixin, FilterView):
    """
    ビュー：一覧表示画面

    以下のパッケージを使用
    ・django-filter 一覧画面(ListView)に検索機能を追加
    https://django-filter.readthedocs.io/en/master/
    """
    model = Item

    # django-filter 設定
    filterset_class = ItemFilterSet
    # django-filter ver2.0対応 クエリ未設定時に全件表示する設定
    strict = False

    # 1ページの表示
    paginate_by = 10

    def get(self, request, **kwargs):
        """
        リクエスト受付
        セッション変数の管理:一覧画面と詳細画面間の移動時に検索条件が維持されるようにする。
        """

        # 一覧画面内の遷移(GETクエリがある)ならクエリを保存する
        if request.GET:
            request.session['query'] = request.GET
        # 詳細画面・登録画面からの遷移(GETクエリはない)ならクエリを復元する
        else:
            request.GET = request.GET.copy()
            if 'query' in request.session.keys():
                for key in request.session['query'].keys():
                    request.GET[key] = request.session['query'][key]

        return super().get(request, **kwargs)

    def get_queryset(self):
        """
        ソート順・デフォルトの絞り込みを指定
        """
        # デフォルトの並び順として、登録時間（降順）をセットする。
        return Item.objects.all().order_by('-created_at')

    def get_context_data(self, *, object_list=None, **kwargs):
        """
        表示データの設定
        """
        # 表示データを追加したい場合は、ここでキーを追加しテンプレート上で表示する
        # 例：kwargs['sample'] = 'sample'
        return super().get_context_data(object_list=object_list, **kwargs)


class ItemDetailView(LoginRequiredMixin, DetailView):
    """
    ビュー：詳細画面
    """
    model = Item

    def get_context_data(self, **kwargs):
        """
        表示データの設定
        """
        # 表示データの追加はここで 例：
        # kwargs['sample'] = 'sample'
        return super().get_context_data(**kwargs)


class ItemCreateView(LoginRequiredMixin, CreateView):
    """
    ビュー：登録画面
    """
    model = Item
    form_class = ItemForm
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        """
        登録処理
        """
        item = form.save(commit=False)
        item.created_by = self.request.user
        item.created_at = timezone.now()
        item.updated_by = self.request.user
        item.updated_at = timezone.now()
        item.sample_11 = AI(item.sample_2)
        item.save()

        return HttpResponseRedirect(self.success_url)


class ItemUpdateView(LoginRequiredMixin, UpdateView):
    """
    ビュー：更新画面
    """
    model = Item
    form_class = ItemForm
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        """
        更新処理
        """
        item = form.save(commit=False)
        item.updated_by = self.request.user
        item.updated_at = timezone.now()
        item.sample_11 = AI(item.sample_2)
        item.save()

        return HttpResponseRedirect(self.success_url)


class ItemDeleteView(LoginRequiredMixin, DeleteView):
    """
    ビュー：削除画面
    """
    model = Item
    success_url = reverse_lazy('index')

    def delete(self, request, *args, **kwargs):
        """
        削除処理
        """
        item = self.get_object()
        item.delete()

        return HttpResponseRedirect(self.success_url)

django/templates/app/item_detail_contents.html
<div class="row">
    <div class="col-5 col-sm-3">
        <p>企業名</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{  item.sample_1|default_if_none:"未入力"  }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>志望動機</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{  item.sample_2|default_if_none:"未入力" }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>志望度</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{  item.sample_3|default_if_none:"未入力" }}</p>
    </div>
</div>

<div class="row">
    <div class="col-5 col-sm-3">
        <p>7_日付</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.sample_7|date:"Y年m月d日" }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>8_日時</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.sample_8|date:"Y年m月d日 G時i分s秒" }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>9_選択肢（固定）</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.get_sample_9_display|default_if_none:"未入力" }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>10_選択肢（マスタ連動）</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.sample_10.get_full_name|default_if_none:"未入力" }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>11_おすすめ</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.sample_11|default_if_none:"未入力"}}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>作成者</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.created_by.get_full_name }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>作成時間</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.created_at|date:"Y/m/d G:i:s" }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>更新者</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.updated_by.get_full_name }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>更新時間</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.updated_at|date:"Y/m/d G:i:s" }}</p>
    </div>
</div>

django/templates/app/item_filter.html
{% extends "./_base.html" %}
{% block content %}
    {% load crispy_forms_tags %}
    <div class="container">
        <div id="myModal" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">検索条件</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form id="filter" method="get">
                        <div class="modal-body">
                            {{ filter.form|crispy }}
                        </div>
                    </form>
                    <div class="modal-footer">
                        <a class="btn btn-outline-dark" data-dismiss="modal">戻る</a>
                        <button type="submit" class="btn btn-outline-dark" form="filter">検索</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <a class="btn btn-secondary filtered" style="visibility:hidden" href="/?page=1">検索を解除</a>
                <div class="float-right mt-1">
                    <a class="btn btn-outline-dark" href="{% url 'create' %}">新規</a>
                    <a class="btn btn-outline-dark" data-toggle="modal" data-target="#myModal" href="#">検索</a>
                </div>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-10 mx-auto">
                {% include "./_pagination.html" %}
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <ul class="list-group">
                    {% for item in item_list %}
                        <li class="list-group-item">
                            {# item_detail_contents.html を参考に必要な項目を追加してください #}
                            <div class="row">
                                <div class="col-5 col-sm-3">
                                    <p>志望企業</p>
                                </div>
                                <div class="col-7 col-sm-9">
                                    <p>{{ item.sample_1|default_if_none:"未入力" }}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-5 col-sm-3">
                                    <p>志望動機</p>
                                </div>
                                <div class="col-7 col-sm-9">
                                    <p>{{ item.sample_2|default_if_none:"未入力" }}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-5 col-sm-3">
                                    <p>志望度</p>
                                </div>
                                <div class="col-7 col-sm-9">
                                    <p>{{ item.sample_3|default_if_none:"未入力" }}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-5 col-sm-3">
                                    <p>おすすめの業界</p>
                                </div>
                                <div class="col-7 col-sm-9">
                                    <p>{{ item.sample_11|default_if_none:"未入力" }}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-5 col-sm-3">
                                    <p>作成者</p>
                                </div>
                                <div class="col-7 col-sm-9">
                                    <p>{{ item.created_by.get_full_name }}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-5 col-sm-3">
                                    <p>作成時間</p>
                                </div>
                                <div class="col-7 col-sm-9">
                                    <p>{{ item.created_at|date:"Y/m/d G:i:s" }}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    <div class="float-right">
                                        <a class="btn btn-outline-dark " href="{% url 'detail' item.pk %}">詳細</a>
                                        <a class="btn btn-outline-dark " href="{% url 'update' item.pk %}">編集</a>
                                        <a class="btn btn-outline-dark " href="{% url 'delete' item.pk %}">削除</a>
                                    </div>
                                </div>
                            </div>
                        </li>
                    {% empty %}
                        <li class="list-group-item">
                            対象のデータがありません
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-10 mx-auto">
                {% include "./_pagination.html" %}
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="float-right mt-1 mb-3">
                    <a class="btn btn-outline-dark" href="{% url 'create' %}">新規</a>
                    <a class="btn btn-outline-dark" data-toggle="modal" data-target="#myModal" href="#">検索</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}